package com.mavyy.yukilockdown;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private LinearLayout body;private Rules.Config config;private Store store;private String page="Home";private boolean bypassRequested;
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private final Handler handler=new Handler(Looper.getMainLooper());private Map<String,Long>usage=Collections.emptyMap();
 public void onCreate(Bundle state){super.onCreate(state);store=Store.get(this);if(state!=null)page=state.getString("page","Home");bypassRequested=getIntent().getBooleanExtra("bypass",false);}
 protected void onResume(){super.onResume();GuardService.appVisible=true;config=store.load();render();worker.execute(()->{Map<String,Long>u;try{u=Device.usage(this);}catch(Exception e){u=Collections.emptyMap();}Map<String,Long>result=u;runOnUiThread(()->{if(!isFinishing()){usage=result;if(page.equals("Home"))render();}});});Warnings.schedule(this);if(bypassRequested){bypassRequested=false;page="Settings";render();bypass(getIntent().getBooleanExtra("strict",false));}}
 protected void onPause(){GuardService.appVisible=false;super.onPause();}
 protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);bypassRequested=i.getBooleanExtra("bypass",false);}
 protected void onSaveInstanceState(Bundle b){b.putString("page",page);super.onSaveInstanceState(b);}
 protected void onDestroy(){handler.removeCallbacksAndMessages(null);worker.shutdownNow();super.onDestroy();}
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 private void save(){if(!store.save(config))throw new IllegalStateException(store.error);Warnings.schedule(this);}
 private void saveSwitch(){try{save();}catch(Exception e){toast(e.getMessage());config=store.load();render();}}
 private void render(){
  LinearLayout root=Ui.column(this);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets.consumeSystemWindowInsets();});
  LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(Ui.dp(this,22),Ui.dp(this,12),Ui.dp(this,22),Ui.dp(this,8));
  ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.icon_lock);logo.setContentDescription(null);header.addView(logo,new LinearLayout.LayoutParams(Ui.dp(this,26),Ui.dp(this,26)));
  TextView brand=new TextView(this);brand.setText("Yuki Lockdown");brand.setTextSize(19);brand.setTypeface(android.graphics.Typeface.create("sans-serif-medium",android.graphics.Typeface.NORMAL));brand.setTextColor(Ui.WHITE);brand.setPadding(Ui.dp(this,10),0,0,0);header.addView(brand,new LinearLayout.LayoutParams(0,-2,1));
  TextView badge=new TextView(this);badge.setText("LOCAL");badge.setTextSize(10);badge.setLetterSpacing(.12f);badge.setTextColor(Ui.BLUE);badge.setPadding(Ui.dp(this,10),Ui.dp(this,7),Ui.dp(this,10),Ui.dp(this,7));badge.setBackground(Ui.shape(this,0xff1b2d40,12));header.addView(badge);root.addView(header);
  ScrollView scroll=new ScrollView(this);scroll.setClipToPadding(false);scroll.setVerticalScrollBarEnabled(false);FrameLayout center=new FrameLayout(this);body=Ui.column(this);body.setPadding(Ui.dp(this,20),Ui.dp(this,8),Ui.dp(this,20),Ui.dp(this,24));FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(Math.min(getResources().getDisplayMetrics().widthPixels,Ui.dp(this,640)),-2,Gravity.CENTER_HORIZONTAL);center.addView(body,cp);LinearLayout pageBody=body;center.addOnLayoutChangeListener((v,left,top,right,bottom,oldLeft,oldTop,oldRight,oldBottom)->{int width=Math.min(right-left,Ui.dp(this,640));if(width>0&&pageBody.getLayoutParams().width!=width){pageBody.getLayoutParams().width=width;pageBody.requestLayout();}});scroll.addView(center);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);nav.setPadding(Ui.dp(this,4),Ui.dp(this,8),Ui.dp(this,4),Ui.dp(this,6));nav.setBackgroundColor(0xff111925);
  String[] destinations={"Home","Apps","Websites","Schedules","Settings"};String[] labels={"Home","Apps","Sites","Plans","Settings"};
  for(int index=0;index<destinations.length;index++){final String name=destinations[index];boolean selected=page.equals(name);LinearLayout item=Ui.column(this);item.setGravity(Gravity.CENTER);item.setPadding(Ui.dp(this,2),Ui.dp(this,8),Ui.dp(this,2),Ui.dp(this,6));item.setMinimumHeight(Ui.dp(this,62));item.setBackground(Ui.ripple(this,selected?0xff23354b:0xff111925,18));item.addView(new NavIcon(this,index,selected?Ui.BLUE:Ui.MUTED),new LinearLayout.LayoutParams(Ui.dp(this,23),Ui.dp(this,23)));TextView label=Ui.text(item,labels[index],11,selected?Ui.BLUE:Ui.MUTED);label.setGravity(Gravity.CENTER);label.setPadding(0,Ui.dp(this,4),0,0);item.setContentDescription(name+(selected?", selected":""));item.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_YES);item.setFocusable(true);item.setSelected(selected);label.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(0,-2,1);np.setMargins(Ui.dp(this,2),0,Ui.dp(this,2),0);nav.addView(item,np);item.setOnClickListener(v->{page=name;config=store.load();render();});}
  root.addView(nav);setContentView(root);if(!store.error.isEmpty())Ui.text(body,store.error,16,Ui.BLUE);
  switch(page){case "Apps"->apps();case "Websites"->websites();case "Schedules"->schedules();case "Settings"->settings();default->home();}
 }
 private void home(){
  List<String>active=new ArrayList<>();Rules.Schedule upcoming=null;ZonedDateTime next=null,now=ZonedDateTime.now();for(Rules.Schedule s:config.schedules){if(s.occurrence(now)!=null)active.add(s.name);ZonedDateTime t=s.nextStart(now);if(t!=null&&(next==null||t.isBefore(next))){next=t;upcoming=s;}}
  Ui.text(body,"A LITTLE SPACE FOR YOU",11,Ui.BLUE).setLetterSpacing(.16f);Ui.text(body,"I’ve got your back, Darling.",27,Ui.WHITE);
  FrameLayout presence=new FrameLayout(this);android.graphics.drawable.GradientDrawable glow=new android.graphics.drawable.GradientDrawable(android.graphics.drawable.GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0xff1d344e,Ui.BG});glow.setCornerRadius(Ui.dp(this,32));presence.setBackground(glow);ImageView yuki=Ui.characterView(this,"neutral");presence.addView(yuki,new FrameLayout.LayoutParams(-1,-1));body.addView(presence,new LinearLayout.LayoutParams(-1,Ui.dp(this,240)));
  LinearLayout hero=Ui.card(body);String state=store.bypassActive()?"Emergency break active":!config.enabled?"Protection paused":!GuardService.connected?"Let’s finish your setup":active.isEmpty()?"Your boundaries, kept. ♡":String.join(" + ",active);Ui.text(hero,state,22,Ui.WHITE);Ui.text(hero,"You choose the rules. I’ll help you follow through.",15,Ui.MUTED);
  if(!GuardService.connected||!Device.usageAllowed(this)){Ui.secondary(hero,"Review setup",()->{page="Settings";render();});}else Ui.text(hero,"Guard connected · on your device",13,Ui.BLUE);
  if(next!=null)Ui.text(hero,"UP NEXT  ·  "+upcoming.name+"  /  "+next.format(DateTimeFormatter.ofPattern("EEE HH:mm")),13,Ui.BLUE);
  LinearLayout today=Ui.card(body);Ui.text(today,"Today, at your pace",21,Ui.WHITE);boolean measured=Device.usageAllowed(this);long total=0;int count=0;
  for(Map.Entry<String,Rules.AppRule>e:config.apps.entrySet()){Rules.AppRule a=e.getValue();if(a.exempt)continue;count++;long used=usage.getOrDefault(e.getKey(),0L);total+=used;Ui.text(today,a.name,16,Ui.WHITE);Ui.text(today,measured?used/60000+" min"+(a.minutes>=0?" of "+a.minutes+" min":" · scheduled access"):"Usage access needed",13,Ui.MUTED);if(measured&&a.minutes>0)Ui.progress(today,used/(a.minutes*60000f));}
  if(count==0)Ui.text(today,"Choose the apps you want a little distance from. Your always-allowed apps stay available.",15,Ui.MUTED);else Ui.text(today,measured?total/60000+" min across protected apps · resets at midnight":"Usage unavailable until access is granted",13,Ui.MUTED);
  Ui.button(body,count==0?"Choose protected apps":"Manage protected apps",()->{page="Apps";render();});Ui.secondary(body,"Plan a Lockdown",()->{page="Schedules";render();});Ui.secondary(body,"Talk to Yuki",()->Device.talk(this));
 }
 private void apps(){
  Ui.text(body,"Protected Apps",28,Ui.WHITE);Ui.text(body,"Set allowances, restrictions and exemptions. System essentials stay available.",15,Ui.MUTED);Ui.button(body,"Browse installed apps",this::chooseInstalled);if(config.apps.isEmpty())Ui.text(body,"Add your AI apps and choose Always Allowed to exempt them.",16,Ui.WHITE);
  for(Map.Entry<String,Rules.AppRule>e:config.apps.entrySet()){String pkg=e.getKey();Rules.AppRule a=e.getValue();LinearLayout card=Ui.card(body);try{ImageView icon=new ImageView(this);icon.setImageDrawable(getPackageManager().getApplicationIcon(pkg));icon.setContentDescription(a.name+" icon");card.addView(icon,new LinearLayout.LayoutParams(Ui.dp(this,40),Ui.dp(this,40)));}catch(Exception ignored){}Ui.text(card,a.name,20,Ui.WHITE);Ui.text(card,a.exempt?"Always Allowed":a.blocked?"Always restricted":a.minutes<0?"Schedules only":a.minutes+" min/day",15,Ui.BLUE);List<String>names=new ArrayList<>();for(Rules.Schedule s:config.schedules)if(s.apps.contains(pkg))names.add(s.name);Ui.text(card,"Schedules: "+(names.isEmpty()?"none":String.join(", ",names)),13,Ui.MUTED);Ui.secondary(card,"Configure",()->editApp(pkg));}
 }
 private void chooseInstalled(){toast("Loading installed apps…");worker.execute(()->{
  Set<String>safe=Device.safe(this);Map<String,String>found=new TreeMap<>();for(ResolveInfo r:getPackageManager().queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER),0))if(!safe.contains(r.activityInfo.packageName))found.put(r.activityInfo.packageName,r.loadLabel(getPackageManager()).toString());List<String>packages=new ArrayList<>(found.keySet());packages.sort(Comparator.comparing(found::get,String.CASE_INSENSITIVE_ORDER));
  runOnUiThread(()->{if(isFinishing())return;LinearLayout panel=form();EditText search=Ui.field(panel,"Search apps","",false);ListView list=new ListView(this);panel.addView(list,new LinearLayout.LayoutParams(-1,Ui.dp(this,340)));List<String>filtered=new ArrayList<>();ArrayAdapter<String>adapter=new ArrayAdapter<>(this,android.R.layout.simple_list_item_1,new ArrayList<>());list.setAdapter(adapter);
   Runnable refresh=()->{String q=search.getText().toString().toLowerCase(Locale.ROOT);filtered.clear();adapter.clear();for(String p:packages)if(found.get(p).toLowerCase(Locale.ROOT).contains(q)||p.contains(q)){filtered.add(p);adapter.add(found.get(p)+"\n"+p);}adapter.notifyDataSetChanged();};refresh.run();search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){refresh.run();}public void afterTextChanged(android.text.Editable e){}});
   AlertDialog d=new AlertDialog.Builder(this).setTitle("Select an app").setView(panel).setNegativeButton("Close",null).create();list.setOnItemClickListener((a,v,pos,id)->{String p=filtered.get(pos);d.dismiss();editApp(p);});d.show();Ui.sheet(d);
  });
 });}
 private LinearLayout form(){LinearLayout l=Ui.column(this);l.setPadding(Ui.dp(this,20),Ui.dp(this,8),Ui.dp(this,20),Ui.dp(this,16));return l;}
 private AlertDialog dialog(String title,LinearLayout l,Runnable commit){ScrollView scroll=new ScrollView(this);scroll.addView(l);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(scroll).setNegativeButton("Cancel",null).setPositiveButton("Save",null).create();d.setOnShowListener(v->{Ui.sheet(d);d.getButton(-1).setOnClickListener(w->{try{commit.run();d.dismiss();render();}catch(Exception e){toast(e.getMessage()==null?"Check your entries.":e.getMessage());}});});return d;}
 private void editApp(String pkg){Rules.AppRule old=config.apps.get(pkg);if(old==null){old=new Rules.AppRule();old.name=Device.label(this,pkg);}Rules.AppRule a=old;LinearLayout l=form();CheckBox exempt=Ui.check(l,"Always Allowed (overrides all rules)",a.exempt),blocked=Ui.check(l,"Always restricted",a.blocked),limited=Ui.check(l,"Use a daily allowance",a.minutes>=0);EditText minutes=Ui.field(l,"Daily minutes: 0–1440",""+(a.minutes<0?20:a.minutes),true);Map<Rules.Schedule,CheckBox>checks=new LinkedHashMap<>();Ui.text(l,"Schedule participation",18,Ui.WHITE);for(Rules.Schedule s:config.schedules)checks.put(s,Ui.check(l,s.name,s.apps.contains(pkg)));
  AlertDialog d=dialog(a.name,l,()->{int m=Integer.parseInt(minutes.getText().toString());if(m<0||m>1440)throw new IllegalArgumentException("Allowance must be 0–1440 minutes.");Rules.AppRule n=new Rules.AppRule();n.name=a.name;n.exempt=exempt.isChecked();n.blocked=blocked.isChecked();n.minutes=limited.isChecked()?m:-1;config.apps.put(pkg,n);for(Map.Entry<Rules.Schedule,CheckBox>e:checks.entrySet()){if(e.getValue().isChecked())e.getKey().apps.add(pkg);else e.getKey().apps.remove(pkg);}save();});
  if(config.apps.containsKey(pkg))Ui.button(l,"Remove app rules",()->{config.apps.remove(pkg);for(Rules.Schedule s:config.schedules)s.apps.remove(pkg);saveSwitch();d.dismiss();render();});d.show();
 }
 private void websites(){Ui.text(body,"Websites",28,Ui.WHITE);Ui.text(body,"Matches domains and subdomains through recognized address bars in Chrome, Brave, Edge, Samsung Internet and Firefox. Hidden bars, private modes, embedded webviews and browser updates can reduce coverage. This is not a network-wide filter.",15,Ui.MUTED);Ui.text(body,GuardService.lastBrowserStatus,13,Ui.BLUE);Ui.button(body,"Add restricted domain",()->editDomain(null));Set<String>all=new TreeSet<>(config.domains);for(Rules.Schedule s:config.schedules)all.addAll(s.domains);for(String host:all){LinearLayout card=Ui.card(body);Ui.text(card,host,20,Ui.WHITE);List<String>names=new ArrayList<>();for(Rules.Schedule s:config.schedules)if(s.domains.contains(host))names.add(s.name);Ui.text(card,config.domains.contains(host)?"Always restricted":"Schedules: "+String.join(", ",names),14,Ui.BLUE);Ui.secondary(card,"Edit website rules",()->editDomain(host));}}
 private void editDomain(String existing){LinearLayout l=form();EditText domain=Ui.field(l,"Domain or URL",existing==null?"":existing,false);domain.setEnabled(existing==null);CheckBox permanent=Ui.check(l,"Always restrict",existing==null||config.domains.contains(existing));Map<Rules.Schedule,CheckBox>checks=new LinkedHashMap<>();for(Rules.Schedule s:config.schedules)checks.put(s,Ui.check(l,s.name,existing!=null&&s.domains.contains(existing)));AlertDialog d=dialog(existing==null?"Add website":existing,l,()->{String host=Rules.domain(domain.getText().toString());if(host.isEmpty())throw new IllegalArgumentException("Enter a domain such as youtube.com.");boolean any=permanent.isChecked();for(CheckBox c:checks.values())any|=c.isChecked();if(!any&&existing==null)throw new IllegalArgumentException("Choose a schedule or Always restrict.");if(permanent.isChecked())config.domains.add(host);else config.domains.remove(host);for(Map.Entry<Rules.Schedule,CheckBox>e:checks.entrySet()){if(e.getValue().isChecked())e.getKey().domains.add(host);else e.getKey().domains.remove(host);}save();});if(existing!=null)Ui.button(l,"Remove everywhere",()->{config.domains.remove(existing);for(Rules.Schedule s:config.schedules)s.domains.remove(existing);saveSwitch();d.dismiss();render();});d.show();}
 private void schedules(){Ui.text(body,"Schedules",28,Ui.WHITE);Ui.text(body,"Start days own overnight windows. Equal times mean 24 hours. Schedules override remaining daily allowance.",15,Ui.MUTED);Ui.button(body,"Create Lockdown",()->editSchedule(null));for(Rules.Schedule s:config.schedules){LinearLayout card=Ui.card(body);Ui.text(card,s.name,23,Ui.WHITE);Ui.text(card,Ui.time(s.start)+"–"+Ui.time(s.end)+" · "+s.mode,16,Ui.BLUE);String[]days={"","Mon","Tue","Wed","Thu","Fri","Sat","Sun"};List<String>labels=new ArrayList<>();for(int d:s.days)labels.add(days[d]);Ui.text(card,String.join(" · ",labels),14,Ui.MUTED);Ui.text(card,s.apps.size()+" apps · "+s.domains.size()+" domains",14,Ui.MUTED);Switch enabled=Ui.toggle(card,"Enabled",s.enabled);enabled.setOnCheckedChangeListener((b,v)->{s.enabled=v;saveSwitch();});Ui.secondary(card,"Edit profile",()->editSchedule(s));}}
 private void editSchedule(Rules.Schedule existing){Rules.Schedule s=existing==null?new Rules.Schedule():existing;LinearLayout l=form();EditText name=Ui.field(l,"Profile name",s.name,false),start=Ui.field(l,"Starts at",Ui.time(s.start),false),end=Ui.field(l,"Ends at",Ui.time(s.end),false);timePicker(start);timePicker(end);Ui.text(l,"Yuki’s outfit",15,Ui.MUTED);String[]modes={"bedtime","focus","outdoors","neutral"};Spinner mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Bedtime","Focus","Outdoors","Neutral"}));mode.setBackground(Ui.shape(this,0xff101722,14));mode.setPadding(Ui.dp(this,12),Ui.dp(this,14),Ui.dp(this,12),Ui.dp(this,14));mode.setSelection(Math.max(0,Arrays.asList(modes).indexOf(s.mode)));l.addView(mode);Ui.text(l,"Repeat on",13,Ui.MUTED);String[]days={"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};List<CheckBox>checks=new ArrayList<>();LinearLayout daysRow=null;for(int i=0;i<7;i++){if(i==0||i==4){daysRow=new LinearLayout(this);l.addView(daysRow,new LinearLayout.LayoutParams(-1,-2));}CheckBox chip=new CheckBox(this);chip.setButtonDrawable((android.graphics.drawable.Drawable)null);chip.setText(days[i].substring(0,3));chip.setTextSize(14);chip.setTextColor(Ui.WHITE);chip.setGravity(Gravity.CENTER);chip.setContentDescription(days[i]);chip.setMinHeight(Ui.dp(this,48));android.graphics.drawable.StateListDrawable states=new android.graphics.drawable.StateListDrawable();states.addState(new int[]{android.R.attr.state_checked},Ui.shape(this,0xff315775,14));states.addState(new int[]{},Ui.shape(this,0xff101722,14));chip.setBackground(states);chip.setChecked(s.days.contains(i+1));LinearLayout.LayoutParams dayLp=new LinearLayout.LayoutParams(0,-2,1);dayLp.setMargins(Ui.dp(this,3),Ui.dp(this,4),Ui.dp(this,3),Ui.dp(this,4));daysRow.addView(chip,dayLp);checks.add(chip);}
  Set<String>selectedApps=new TreeSet<>(s.apps),selectedDomains=new TreeSet<>(s.domains);Ui.button(l,"Choose protected apps",()->multiSelect("Apps",new ArrayList<>(config.apps.keySet()),selectedApps,true));Set<String>known=new TreeSet<>(config.domains);for(Rules.Schedule p:config.schedules)known.addAll(p.domains);Ui.button(l,"Choose known websites",()->multiSelect("Websites",new ArrayList<>(known),selectedDomains,false));EditText extra=Ui.field(l,"Additional domains (comma separated)","",false),warnings=Ui.field(l,"Warning minutes before start (blank disables)",join(s.warnings),false);CheckBox enabled=Ui.check(l,"Enabled",s.enabled),strict=Ui.check(l,"Strict: bypass requires at least 60 seconds",s.strict);Ui.text(l,"Overlaps combine. Strict profiles take display priority, then stable IDs. Owner editing remains available.",13,Ui.MUTED);
  AlertDialog d=dialog("Lockdown profile",l,()->{String n=name.getText().toString().trim();if(n.isEmpty())throw new IllegalArgumentException("Give this profile a name.");Rules.Schedule out=new Rules.Schedule();out.id=s.id;out.name=n;out.mode=modes[mode.getSelectedItemPosition()];out.start=Ui.time(start.getText().toString());out.end=Ui.time(end.getText().toString());out.days.clear();for(int i=0;i<7;i++)if(checks.get(i).isChecked())out.days.add(i+1);if(out.days.isEmpty())throw new IllegalArgumentException("Choose at least one start day.");out.apps.addAll(selectedApps);out.domains.addAll(selectedDomains);String e=extra.getText().toString().trim();if(!e.isEmpty())for(String raw:e.split(",")){String host=Rules.domain(raw);if(host.isEmpty())throw new IllegalArgumentException("Invalid domain: "+raw);out.domains.add(host);}out.warnings.clear();String w=warnings.getText().toString().trim();if(!w.isEmpty())for(String v:w.split(",")){int m=Integer.parseInt(v.trim());if(m<1||m>120)throw new IllegalArgumentException("Warning minutes must be 1–120.");out.warnings.add(m);}out.enabled=enabled.isChecked();out.strict=strict.isChecked();if(out.apps.isEmpty()&&out.domains.isEmpty())throw new IllegalArgumentException("Choose an app or domain.");int index=config.schedules.indexOf(existing);if(index<0)config.schedules.add(out);else config.schedules.set(index,out);save();});if(existing!=null)Ui.button(l,"Delete profile",()->new AlertDialog.Builder(this).setMessage("Delete "+s.name+"?").setNegativeButton("Cancel",null).setPositiveButton("Delete",(a,b)->{config.schedules.remove(existing);saveSwitch();d.dismiss();render();}).show());d.show();
 }
 private String join(Collection<Integer>v){List<String>s=new ArrayList<>();for(int i:v)s.add(""+i);return String.join(",",s);}
 private void multiSelect(String title,List<String>keys,Set<String>selection,boolean apps){if(keys.isEmpty()){toast("Add apps/websites first, or enter additional domains below.");return;}String[]labels=new String[keys.size()];boolean[]checked=new boolean[keys.size()];Set<String>draft=new TreeSet<>(selection);for(int i=0;i<keys.size();i++){labels[i]=apps?Device.label(this,keys.get(i)):keys.get(i);checked[i]=selection.contains(keys.get(i));}new AlertDialog.Builder(this).setTitle(title).setMultiChoiceItems(labels,checked,(d,i,v)->{if(v)draft.add(keys.get(i));else draft.remove(keys.get(i));}).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{selection.clear();selection.addAll(draft);toast(selection.size()+" selected");}).show();}
 private void explain(String title,String why,Intent intent){new AlertDialog.Builder(this).setTitle(title).setMessage(why).setNegativeButton("Not now",null).setPositiveButton("Open Android settings",(d,w)->{try{startActivity(intent);}catch(Exception e){toast("This settings page is unavailable on your device.");}}).show();}
 private void settings(){
  Ui.text(body,"Settings & setup",28,Ui.WHITE);LinearLayout setup=Ui.card(body);Ui.text(setup,"1 · Enable Yuki’s guard",21,Ui.WHITE);Ui.text(setup,"Status: "+(GuardService.connected?"Connected":Device.accessibilityEnabled(this)?"Enabled; waiting for Android":"Disabled"),15,Ui.BLUE);
  Ui.secondary(setup,"Accessibility setup",()->explain("Allow Yuki to enforce your rules?","Yuki detects foreground apps and reads only supported browser address-bar nodes. It uses an accessibility overlay to intervene. No messages, page text or browsing history are saved or transmitted. You can disable it any time. Sideloaded apps may first need App info → menu → Allow restricted settings.",new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));
  Ui.text(setup,"2 · Daily allowances",21,Ui.WHITE);Ui.text(setup,Device.usageAllowed(this)?"Usage access granted":"Usage access not granted",15,Ui.BLUE);Ui.secondary(setup,"Usage access setup",()->explain("Allow usage access?","Android’s local activity timestamps measure foreground use since local midnight. Without access, scheduled/permanent restrictions work but timed allowances cannot be measured.",new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS,Uri.parse("package:"+getPackageName()))));
  Ui.text(setup,"3 · Advance warnings",21,Ui.WHITE);Ui.text(setup,getSystemService(NotificationManager.class).areNotificationsEnabled()?"Notifications available":"Notifications disabled",15,Ui.BLUE);Ui.secondary(setup,"Notification setup",()->new AlertDialog.Builder(this).setTitle("Allow advance reminders?").setMessage("Notifications warn before schedules begin. Android may delay them under battery saving; enforcement does not depend on notification delivery.").setNegativeButton("Not now",null).setPositiveButton("Continue",(d,w)->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},3);else startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));}).show());
  Ui.text(setup,"Overlay is supplied by the accessibility service; no separate Draw over other apps permission is required.",14,Ui.MUTED);Ui.secondary(setup,"App & battery settings",()->explain("Service reliability","Some phones suspend accessibility services under aggressive battery management. Review battery restrictions if interventions stop. Android can still suspend or revoke services.",new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()))));
  LinearLayout prefs=Ui.card(body);Ui.text(prefs,"Your preferences",21,Ui.WHITE);Switch enabled=Ui.toggle(prefs,"Protection enabled",config.enabled),websites=Ui.toggle(prefs,"Supported-browser website blocking",config.websites),reactions=Ui.toggle(prefs,"Escalate repeated-attempt reactions",config.reactions);enabled.setOnCheckedChangeListener((b,v)->{config.enabled=v;saveSwitch();});websites.setOnCheckedChangeListener((b,v)->{config.websites=v;saveSwitch();});reactions.setOnCheckedChangeListener((b,v)->{config.reactions=v;saveSwitch();});Switch reduced=Ui.toggle(prefs,"Reduce motion",getSharedPreferences("presentation",0).getBoolean("reduce_motion",false));reduced.setOnCheckedChangeListener((button,value)->getSharedPreferences("presentation",0).edit().putBoolean("reduce_motion",value).apply());Switch companion=Ui.toggle(prefs,"Pocket Yuki companion",getSharedPreferences("pocket_yuki",0).getBoolean("enabled",true));companion.setOnCheckedChangeListener((button,value)->getSharedPreferences("pocket_yuki",0).edit().putBoolean("enabled",value).apply());Ui.text(prefs,"Tap Pocket Yuki for Boop, Talk and Move. After Move, drag her to place her. She blinks, waves and wanders near her saved spot. She needs the guard connected and hides during lockouts, keyboard use, screen lock and while this app is open. Feed data and a custom hoodie-grab pose are coming later.",14,Ui.MUTED);Switch wander=Ui.toggle(prefs,"Let Yuki wander nearby",getSharedPreferences("pocket_yuki",0).getBoolean("wander",true));wander.setOnCheckedChangeListener((button,value)->getSharedPreferences("pocket_yuki",0).edit().putBoolean("wander",value).apply());Ui.secondary(prefs,"Reset Yuki’s position",()->{getSharedPreferences("pocket_yuki",0).edit().remove("x").remove("y").apply();GuardService.resetCompanionPosition();toast("Yuki will return to her default spot.");});Ui.secondary(prefs,"Preview Yuki’s entrance",this::previewYuki);Ui.text(prefs,"Charcoal / icy blue · follows system font size",14,Ui.MUTED);
  Ui.secondary(prefs,"AI destination",()->{LinearLayout l=form();EditText pkg=Ui.field(l,"Android package",config.aiPackage,false),url=Ui.field(l,"Fallback HTTPS URL",config.aiUrl,false);dialog("Talk to Yuki",l,()->{String p=pkg.getText().toString().trim(),u=url.getText().toString().trim();if(!p.matches("[a-zA-Z][a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]+)+")||!u.startsWith("https://")||Rules.domain(u).isEmpty())throw new IllegalArgumentException("Enter a valid package and HTTPS URL.");config.aiPackage=p;config.aiUrl=u;save();}).show();});
  Ui.secondary(prefs,"Emergency bypass preferences",()->{LinearLayout l=form();EditText minutes=Ui.field(l,"Break duration: 1–60 minutes",""+config.bypassMinutes,true),seconds=Ui.field(l,"Countdown: 5–120 seconds",""+config.bypassWaitSeconds,true);dialog("Emergency friction",l,()->{int m=Integer.parseInt(minutes.getText().toString()),s=Integer.parseInt(seconds.getText().toString());if(m<1||m>60||s<5||s>120)throw new IllegalArgumentException("Use the displayed ranges.");config.bypassMinutes=m;config.bypassWaitSeconds=s;save();}).show();});Ui.secondary(prefs,"Start emergency bypass",()->bypass(false));if(store.bypassActive())Ui.secondary(prefs,"End bypass now",()->{store.clearBypass();render();});
  LinearLayout diag=Ui.card(body);Ui.text(diag,"Diagnostics & privacy",21,Ui.WHITE);Ui.text(diag,GuardService.status+"\n"+GuardService.lastBrowserStatus+"\nTime zone: "+ZoneId.systemDefault()+"\nConfiguration: "+(store.error.isEmpty()?"readable":store.error)+"\nNo Internet permission. No analytics or ads. Talk to Yuki opens your chosen app.",14,Ui.MUTED);Ui.text(diag,"Website coverage depends on browser address-bar accessibility. Unsupported browsers, embedded webviews, hidden bars and updates may bypass it. Exempt browsers bypass domain rules too. For stronger coverage, restrict unsupported browser apps. Split-screen, force-stop and revoked permissions can weaken enforcement.",14,Ui.MUTED);
 }
 private void timePicker(EditText field){field.setFocusable(false);field.setClickable(true);field.setContentDescription(field.getText()+", choose time");field.setOnClickListener(v->{int minute=Ui.time(field.getText().toString());new TimePickerDialog(this,(picker,h,m)->{field.setText(Ui.time(h*60+m));field.setContentDescription(field.getText()+", choose time");},minute/60,minute%60,true).show();});}
 private void previewYuki(){Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);View content=Intervention.create(this,"bedtime","Bedtime preview","Darling, it’s bedtime. Your feed can wait. ♡",1,()->d.dismiss(),()->{d.dismiss();Device.talk(this);},()->d.dismiss(),true);d.setContentView(content);if(d.getWindow()!=null){d.getWindow().setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));d.getWindow().setDimAmount(0);}d.show();if(d.getWindow()!=null)d.getWindow().setLayout(-1,-1);}
 private void bypass(boolean strict){for(Rules.Schedule s:config.schedules)if(s.strict&&s.occurrence(ZonedDateTime.now())!=null)strict=true;int wait=Math.max(config.bypassWaitSeconds,strict?60:0);LinearLayout l=form();Ui.text(l,"You retain control. Pause restrictions for "+config.bypassMinutes+" minutes. Your reason stays on this screen and is not saved.",16,Ui.WHITE);EditText reason=Ui.field(l,"Why do you need a break?","",false);AlertDialog d=new AlertDialog.Builder(this).setTitle("Emergency bypass").setView(l).setNegativeButton("Cancel",null).setPositiveButton("Wait…",null).create();long until=SystemClock.elapsedRealtime()+wait*1000L;Runnable countdown=new Runnable(){public void run(){if(!d.isShowing())return;long left=Math.max(0,(until-SystemClock.elapsedRealtime()+999)/1000);Button b=d.getButton(-1);b.setText(left>0?"Wait "+left+"s":"Confirm break");b.setEnabled(left==0);if(left>0)handler.postDelayed(this,250);}};d.setOnShowListener(v->{Ui.sheet(d);d.getButton(-1).setOnClickListener(w->{if(SystemClock.elapsedRealtime()<until)return;if(reason.getText().toString().trim().length()<4){toast("Enter a short reason first.");return;}try{store.bypass(config.bypassMinutes);d.dismiss();toast("Break started. Your rules resume automatically.");render();}catch(Exception e){toast("Could not save the bypass. You can still edit your rules.");}});countdown.run();});d.show();}
}
