package com.mavyy.yukilockdown;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private RoomScene scene;private final RoomDialogue flow=new RoomDialogue();private LinearLayout body;private Rules.Config config;private Store store;
 private String page="",editorKind="",editorKey="",savedConfig="";private boolean bypassRequested,resumed;
 private boolean draftReduced,draftCompanion,draftWander,resetPosition;private int draftSize;
 private Object backCallback;private Bundle restoration;private TextView guardLabel,usageLabel,notificationLabel;
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private final Handler handler=new Handler(Looper.getMainLooper());private Map<String,Long>usage=Collections.emptyMap();
 public void onCreate(Bundle state){super.onCreate(state);store=Store.get(this);config=store.load();savedConfig=encoded(config);loadPresentation();restoration=state;
  if(state!=null){flow.restore(state.getString("flow","QUIET:0:"));page=state.getString("page","");editorKind=state.getString("editor","");editorKey=state.getString("key","");try{config=Store.decode(state.getString("draft",savedConfig));}catch(Exception ignored){}draftReduced=state.getBoolean("reduced",draftReduced);draftCompanion=state.getBoolean("companion",draftCompanion);draftWander=state.getBoolean("wander",draftWander);draftSize=state.getInt("size",draftSize);resetPosition=state.getBoolean("reset",false);}
  getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);
  scene=new RoomScene(this,flow,this::openPage);setContentView(scene);if(Build.VERSION.SDK_INT>=33){android.window.OnBackInvokedCallback callback=()->{if(!scene.back())finish();};backCallback=callback;getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,callback);}restorePanel();bypassRequested=state==null&&getIntent().getBooleanExtra("bypass",false);
 }
 protected void onResume(){super.onResume();resumed=true;GuardService.appVisible=true;scene.resume();refreshSetup();worker.execute(()->{Map<String,Long>u;try{u=Device.usage(this);}catch(Exception e){u=Collections.emptyMap();}Map<String,Long>result=u;runOnUiThread(()->{if(!isFinishing()&&!isDestroyed())usage=result;});});Warnings.schedule(this);if(bypassRequested){bypassRequested=false;bypass(getIntent().getBooleanExtra("strict",false));}}
 protected void onPause(){resumed=false;scene.pause();GuardService.appVisible=false;super.onPause();}
 protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);bypassRequested=i.getBooleanExtra("bypass",false);if(resumed&&bypassRequested){bypassRequested=false;bypass(i.getBooleanExtra("strict",false));}}
 protected void onSaveInstanceState(Bundle b){b.putString("flow",flow.checkpoint());b.putString("page",scene.currentPanel()==null?"":page);b.putString("editor",editorKind);b.putString("key",editorKey);b.putString("draft",encoded(config));b.putBoolean("reduced",draftReduced);b.putBoolean("companion",draftCompanion);b.putBoolean("wander",draftWander);b.putInt("size",draftSize);b.putBoolean("reset",resetPosition);if(scene.currentPanel()!=null&&!editorKind.equals("bypass"))b.putBundle("form",RoomFormState.capture(scene.currentPanel().content()));super.onSaveInstanceState(b);}
 protected void onDestroy(){handler.removeCallbacksAndMessages(null);worker.shutdownNow();if(Build.VERSION.SDK_INT>=33&&backCallback!=null)getOnBackInvokedDispatcher().unregisterOnBackInvokedCallback((android.window.OnBackInvokedCallback)backCallback);scene.pause();super.onDestroy();}
 @SuppressWarnings("deprecation") public void onBackPressed(){if(!scene.back())super.onBackPressed();}
 private String encoded(Rules.Config value){try{return Store.encode(value);}catch(Exception e){return "";}}
 private void loadPresentation(){var presentation=getSharedPreferences("presentation",0);var pocket=getSharedPreferences("pocket_yuki",0);draftReduced=presentation.getBoolean("reduce_motion",false);draftCompanion=pocket.getBoolean("enabled",true);draftWander=pocket.getBoolean("wander",true);draftSize=CompanionSize.clamp(pocket.getInt("size_dp",CompanionSize.DEFAULT));resetPosition=false;}
 private void savePresentation(){
  var presentation=getSharedPreferences("presentation",0);var pocket=getSharedPreferences("pocket_yuki",0);
  if(presentation.getBoolean("reduce_motion",false)!=draftReduced&&!presentation.edit().putBoolean("reduce_motion",draftReduced).commit())throw new IllegalStateException("Could not save motion preference. Please retry.");
  if((pocket.getBoolean("enabled",true)!=draftCompanion||pocket.getBoolean("wander",true)!=draftWander||pocket.getInt("size_dp",CompanionSize.DEFAULT)!=draftSize||resetPosition)){
   var changes=pocket.edit().putBoolean("enabled",draftCompanion).putBoolean("wander",draftWander).putInt("size_dp",draftSize);if(resetPosition)changes.remove("x").remove("y");if(!changes.commit())throw new IllegalStateException("Could not save companion preferences. Please retry.");if(resetPosition){GuardService.resetCompanionPosition();resetPosition=false;}
  }scene.resume();
 }
 private void restorePanel(){if(page.isEmpty()){if(flow.step()==RoomDialogue.Step.PANEL)flow.returnToDialogue("I’m here, Darling. ♡");scene.updateDialogue();return;}String kind=editorKind,key=editorKey,route=page;openPage(route);switch(kind){case "app"->editApp(key);case "domain"->editDomain(key.isEmpty()?null:key);case "schedule"->editSchedule(config.schedules.stream().filter(v->v.id.equals(key)).findFirst().orElse(null));case "ai"->aiDestination();case "friction"->bypassPreferences();case "removeApp"->removeApp(key);case "removeDomain"->removeDomain(key);case "removeSchedule"->removeSchedule(key);case "picker"->chooseInstalled();case "bypass"->bypass(false);default->{}}if(restoration!=null&&scene.currentPanel()!=null&&!kind.equals("bypass")&&!kind.equals("picker")&&!kind.equals("removal"))RoomFormState.restore(scene.currentPanel().content(),restoration.getBundle("form"));if(!kind.equals("picker"))restoration=null;}
 private void refreshSetup(){if(guardLabel!=null)guardLabel.setText("Status: "+(GuardService.connected?"Connected":Device.accessibilityEnabled(this)?"Enabled; waiting for Android":"Disabled"));if(usageLabel!=null)usageLabel.setText(Device.usageAllowed(this)?"Usage access granted":"Usage access not granted");if(notificationLabel!=null)notificationLabel.setText(getSystemService(NotificationManager.class).areNotificationsEnabled()?"Notifications available":"Notifications disabled");}
 private void companionSizeControl(LinearLayout parent){
  int value=draftSize;
  TextView label=Ui.text(parent,"Floating Yuki size: "+value+" dp",16,Ui.WHITE);
  Ui.text(parent,"Adjust the companion floating over other apps. Your chosen size is saved when you close the panel.",14,Ui.MUTED);
  SeekBar slider=new SeekBar(this);slider.setMax(CompanionSize.MAX-CompanionSize.MIN);slider.setProgress(value-CompanionSize.MIN);slider.setMinimumHeight(Ui.dp(this,48));slider.setContentDescription("Floating Yuki size, 80 to 240 dp");parent.addView(slider,new LinearLayout.LayoutParams(-1,-2));
  slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){
   public void onProgressChanged(SeekBar bar,int progress,boolean fromUser){int dp=CompanionSize.MIN+progress;label.setText("Floating Yuki size: "+dp+" dp");draftSize=dp;}
   public void onStartTrackingTouch(SeekBar bar){}
   public void onStopTrackingTouch(SeekBar bar){}
  });
 }
 private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 private void save(){if(!store.error.isEmpty())throw new IllegalStateException(store.error);String next=encoded(config);try{Store.decode(next);}catch(Exception e){throw new IllegalArgumentException("Check the rule settings before saving.");}if(!next.equals(savedConfig)){if(!store.save(config))throw new IllegalStateException(store.error);savedConfig=next;Warnings.schedule(this);}}
 private void attempt(Runnable action){String before=encoded(config),savedBefore=savedConfig;try{action.run();}catch(Exception e){if(savedConfig.equals(savedBefore))try{config=Store.decode(before);}catch(Exception ignored){}if(scene.currentPanel()!=null)scene.currentPanel().reportError(e);else toast(e.getMessage());}}
 private void discard(){config=store.load();savedConfig=encoded(config);loadPresentation();if(scene.currentPanel()!=null)scene.currentPanel().discard();page="";editorKind="";}
 private void openPage(String destination){
  page=destination;editorKind="";editorKey="";guardLabel=null;usageLabel=null;notificationLabel=null;body=form();
  switch(destination){case "Protected Apps","Apps"->apps();case "Sites","Websites"->websites();case "Plans","Schedules"->schedules();case "Settings"->settings();default->talk();}
  if(!store.error.isEmpty())Ui.text(body,store.error,15,Ui.BLUE);
  Ui.text(body,"× saves changes and returns to our conversation.",13,Ui.MUTED);Ui.secondary(body,"Discard unsaved changes",this::discard);
  scene.createPanel(destination,body,()->{save();savePresentation();page="";editorKind="";},true).show();
 }
 private void talk(){
  Ui.text(body,"A little time together",24,Ui.WHITE);Ui.text(body,"I’m glad you’re here, Darling. What’s on your mind? ♡",17,Ui.BLUE);
  Ui.secondary(body,"A quiet moment",()->{page="";editorKind="";scene.reply("You don’t have to fill every quiet moment. Settle in with me for a little while. ♡");});
  TextView boundaryStatus=Ui.text(body,"",15,Ui.MUTED);boundaryStatus.setVisibility(View.GONE);
  Ui.secondary(body,"How are my boundaries doing?",()->{String state=!config.enabled?"Protection is paused.":store.bypassActive()?"Your emergency break is active.":GuardService.connected?"Your guard is connected.":"Your guard needs setup before it can protect your boundaries.";long total=0;for(String pkg:config.apps.keySet())if(!config.apps.get(pkg).exempt)total+=usage.getOrDefault(pkg,0L);boundaryStatus.setText(state+"\n"+config.apps.size()+" configured apps · "+config.domains.size()+" permanent domains · "+config.schedules.size()+" plans\n"+(Device.usageAllowed(this)?total/60000+" minutes across protected apps today":"Daily usage needs Usage access."));boundaryStatus.setVisibility(View.VISIBLE);});
  Ui.secondary(body,"Settings & setup",()->openPage("Settings"));
  Ui.secondary(body,"Open AI chat",()->attempt(()->{save();savePresentation();Device.talk(this);}));Ui.text(body,"Room dialogue is local. Open AI chat launches your configured app.",13,Ui.MUTED);
 }
 private void apps(){
  Ui.text(body,"Protected Apps",28,Ui.WHITE);Ui.text(body,"Set allowances, restrictions and exemptions. System essentials stay available.",15,Ui.MUTED);Ui.button(body,"Browse installed apps",this::chooseInstalled);if(config.apps.isEmpty())Ui.text(body,"Add your AI apps and choose Always Allowed to exempt them.",16,Ui.WHITE);
  for(Map.Entry<String,Rules.AppRule>e:config.apps.entrySet()){String pkg=e.getKey();Rules.AppRule a=e.getValue();LinearLayout card=Ui.card(body);try{ImageView icon=new ImageView(this);icon.setImageDrawable(getPackageManager().getApplicationIcon(pkg));icon.setContentDescription(a.name+" icon");card.addView(icon,new LinearLayout.LayoutParams(Ui.dp(this,40),Ui.dp(this,40)));}catch(Exception ignored){}Ui.text(card,a.name,20,Ui.WHITE);Ui.text(card,a.exempt?"Always Allowed":a.blocked?"Always restricted":a.minutes<0?"Schedules only":a.minutes+" min/day",15,Ui.BLUE);if(!a.exempt)Ui.text(card,Device.usageAllowed(this)?"Today: "+usage.getOrDefault(pkg,0L)/60000+" min":"Usage access needed for today’s measurement",13,Ui.MUTED);List<String>names=new ArrayList<>();for(Rules.Schedule s:config.schedules)if(s.apps.contains(pkg))names.add(s.name);Ui.text(card,"Schedules: "+(names.isEmpty()?"none":String.join(", ",names)),13,Ui.MUTED);Ui.secondary(card,"Configure",()->editApp(pkg));}
 }
 private void chooseInstalled(){
  editorKind="picker";editorKey="";LinearLayout loading=form();Ui.text(loading,"Finding installed apps…",17,Ui.WHITE);RoomPanel picker=scene.createPanel("Choose an app",loading,()->{save();savePresentation();},true);picker.show();
  worker.execute(()->{
   Set<String>safe=Device.safe(this);Map<String,String>found=new TreeMap<>();for(ResolveInfo r:getPackageManager().queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER),0))if(!safe.contains(r.activityInfo.packageName))found.put(r.activityInfo.packageName,r.loadLabel(getPackageManager()).toString());List<String>packages=new ArrayList<>(found.keySet());packages.sort(Comparator.comparing(found::get,String.CASE_INSENSITIVE_ORDER));
   runOnUiThread(()->{if(isFinishing()||isDestroyed()||!picker.isShowing())return;LinearLayout panel=form();EditText search=Ui.field(panel,"Search apps","",false);LinearLayout results=Ui.column(this);panel.addView(results);picker.setContent(panel);
    Runnable refresh=()->{String q=search.getText().toString().toLowerCase(Locale.ROOT);results.removeAllViews();int matches=0;for(String pkg:packages)if(found.get(pkg).toLowerCase(Locale.ROOT).contains(q)||pkg.contains(q)){Ui.secondary(results,found.get(pkg),()->editApp(pkg));matches++;}if(matches==0)Ui.text(results,"No matching apps.",15,Ui.MUTED);};refresh.run();search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){refresh.run();}public void afterTextChanged(android.text.Editable e){}});if(restoration!=null){RoomFormState.restore(panel,restoration.getBundle("form"));restoration=null;}
   });
  });
 }
 private LinearLayout form(){LinearLayout l=Ui.column(this);l.setPadding(Ui.dp(this,20),Ui.dp(this,8),Ui.dp(this,20),Ui.dp(this,16));return l;}
 private RoomPanel dialog(String title,LinearLayout l,Runnable commit){
  Ui.text(l,"Use × above to save and return to Yuki.",13,Ui.MUTED);Ui.secondary(l,"Discard unsaved changes",this::discard);
  return scene.createPanel(title,l,()->{commit.run();savePresentation();page="";editorKind="";},true);
 }
 private void editApp(String pkg){editorKind="app";editorKey=pkg;Rules.AppRule old=config.apps.get(pkg);if(old==null){old=new Rules.AppRule();old.name=Device.label(this,pkg);}Rules.AppRule a=old;LinearLayout l=form();CheckBox exempt=Ui.check(l,"Always Allowed (overrides all rules)",a.exempt),blocked=Ui.check(l,"Always restricted",a.blocked),limited=Ui.check(l,"Use a daily allowance",a.minutes>=0);EditText minutes=Ui.field(l,"Daily minutes: 0–1440",""+(a.minutes<0?20:a.minutes),true);Map<Rules.Schedule,CheckBox>checks=new LinkedHashMap<>();Ui.text(l,"Schedule participation",18,Ui.WHITE);for(Rules.Schedule s:config.schedules)checks.put(s,Ui.check(l,s.name,s.apps.contains(pkg)));
  RoomPanel d=dialog(a.name,l,()->{int m=Integer.parseInt(minutes.getText().toString());if(m<0||m>1440)throw new IllegalArgumentException("Allowance must be 0–1440 minutes.");Rules.AppRule n=new Rules.AppRule();n.name=a.name;n.exempt=exempt.isChecked();n.blocked=blocked.isChecked();n.minutes=limited.isChecked()?m:-1;config.apps.put(pkg,n);for(Map.Entry<Rules.Schedule,CheckBox>e:checks.entrySet()){if(e.getValue().isChecked())e.getKey().apps.add(pkg);else e.getKey().apps.remove(pkg);}save();});
  if(config.apps.containsKey(pkg))Ui.button(l,"Remove app rules",()->removeApp(pkg));d.show();
 }
 private void websites(){Ui.text(body,"Websites",28,Ui.WHITE);Ui.text(body,"Matches domains and subdomains through recognized address bars in Chrome, Brave, Edge, Samsung Internet and Firefox. Hidden bars, private modes, embedded webviews and browser updates can reduce coverage. This is not a network-wide filter.",15,Ui.MUTED);Ui.text(body,GuardService.lastBrowserStatus,13,Ui.BLUE);Ui.button(body,"Add restricted domain",()->editDomain(null));Set<String>all=new TreeSet<>(config.domains);for(Rules.Schedule s:config.schedules)all.addAll(s.domains);for(String host:all){LinearLayout card=Ui.card(body);Ui.text(card,host,20,Ui.WHITE);List<String>names=new ArrayList<>();for(Rules.Schedule s:config.schedules)if(s.domains.contains(host))names.add(s.name);Ui.text(card,config.domains.contains(host)?"Always restricted":"Schedules: "+String.join(", ",names),14,Ui.BLUE);Ui.secondary(card,"Edit website rules",()->editDomain(host));}}
 private void editDomain(String existing){editorKind="domain";editorKey=existing==null?"":existing;LinearLayout l=form();EditText domain=Ui.field(l,"Domain or URL",existing==null?"":existing,false);domain.setEnabled(existing==null);CheckBox permanent=Ui.check(l,"Always restrict",existing==null||config.domains.contains(existing));Map<Rules.Schedule,CheckBox>checks=new LinkedHashMap<>();for(Rules.Schedule s:config.schedules)checks.put(s,Ui.check(l,s.name,existing!=null&&s.domains.contains(existing)));RoomPanel d=dialog(existing==null?"Add website":existing,l,()->{String host=Rules.domain(domain.getText().toString());if(host.isEmpty())throw new IllegalArgumentException("Enter a domain such as youtube.com.");boolean any=permanent.isChecked();for(CheckBox c:checks.values())any|=c.isChecked();if(!any&&existing==null)throw new IllegalArgumentException("Choose a schedule or Always restrict.");if(permanent.isChecked())config.domains.add(host);else config.domains.remove(host);for(Map.Entry<Rules.Schedule,CheckBox>e:checks.entrySet()){if(e.getValue().isChecked())e.getKey().domains.add(host);else e.getKey().domains.remove(host);}save();});if(existing!=null)Ui.button(l,"Remove everywhere",()->removeDomain(existing));d.show();}
 private void schedules(){Ui.text(body,"Schedules",28,Ui.WHITE);Ui.text(body,"Start days own overnight windows. Equal times mean 24 hours. Schedules override remaining daily allowance.",15,Ui.MUTED);Ui.button(body,"Create Lockdown",()->editSchedule(null));for(Rules.Schedule s:config.schedules){LinearLayout card=Ui.card(body);Ui.text(card,s.name,23,Ui.WHITE);Ui.text(card,Ui.time(s.start)+"–"+Ui.time(s.end)+" · "+s.mode,16,Ui.BLUE);String[]days={"","Mon","Tue","Wed","Thu","Fri","Sat","Sun"};List<String>labels=new ArrayList<>();for(int d:s.days)labels.add(days[d]);Ui.text(card,String.join(" · ",labels),14,Ui.MUTED);Ui.text(card,s.apps.size()+" apps · "+s.domains.size()+" domains",14,Ui.MUTED);Switch enabled=Ui.toggle(card,"Enabled",s.enabled);enabled.setOnCheckedChangeListener((b,v)->{s.enabled=v;});Ui.secondary(card,"Edit profile",()->editSchedule(s));}}
 private void editSchedule(Rules.Schedule existing){editorKind="schedule";editorKey=existing==null?"":existing.id;Rules.Schedule s=existing==null?new Rules.Schedule():existing;LinearLayout l=form();EditText name=Ui.field(l,"Profile name",s.name,false),start=Ui.field(l,"Starts at",Ui.time(s.start),false),end=Ui.field(l,"Ends at",Ui.time(s.end),false);timePicker(start);timePicker(end);Ui.text(l,"Yuki’s outfit",15,Ui.MUTED);String[]modes={"bedtime","focus","outdoors","neutral"};Spinner mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Bedtime","Focus","Outdoors","Neutral"}));mode.setBackground(Ui.shape(this,0xff101722,14));mode.setPadding(Ui.dp(this,12),Ui.dp(this,14),Ui.dp(this,12),Ui.dp(this,14));mode.setSelection(Math.max(0,Arrays.asList(modes).indexOf(s.mode)));l.addView(mode);Ui.text(l,"Repeat on",13,Ui.MUTED);String[]days={"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};List<CheckBox>checks=new ArrayList<>();LinearLayout daysRow=null;for(int i=0;i<7;i++){if(i==0||i==4){daysRow=new LinearLayout(this);l.addView(daysRow,new LinearLayout.LayoutParams(-1,-2));}CheckBox chip=new CheckBox(this);chip.setButtonDrawable((android.graphics.drawable.Drawable)null);chip.setText(days[i].substring(0,3));chip.setTextSize(14);chip.setTextColor(Ui.WHITE);chip.setGravity(Gravity.CENTER);chip.setContentDescription(days[i]);chip.setMinHeight(Ui.dp(this,48));android.graphics.drawable.StateListDrawable states=new android.graphics.drawable.StateListDrawable();states.addState(new int[]{android.R.attr.state_checked},Ui.shape(this,0xff315775,14));states.addState(new int[]{},Ui.shape(this,0xff101722,14));chip.setBackground(states);chip.setChecked(s.days.contains(i+1));LinearLayout.LayoutParams dayLp=new LinearLayout.LayoutParams(0,-2,1);dayLp.setMargins(Ui.dp(this,3),Ui.dp(this,4),Ui.dp(this,3),Ui.dp(this,4));daysRow.addView(chip,dayLp);checks.add(chip);}
  Set<String>selectedApps=new TreeSet<>(s.apps),selectedDomains=new TreeSet<>(s.domains);
  Ui.text(l,"Protected apps in this plan",17,Ui.WHITE);for(String pkg:config.apps.keySet()){CheckBox check=Ui.check(l,config.apps.get(pkg).name,selectedApps.contains(pkg));check.setOnCheckedChangeListener((v,checked)->{if(checked)selectedApps.add(pkg);else selectedApps.remove(pkg);});}
  Set<String>known=new TreeSet<>(config.domains);for(Rules.Schedule plan:config.schedules)known.addAll(plan.domains);Ui.text(l,"Known sites in this plan",17,Ui.WHITE);for(String host:known){CheckBox check=Ui.check(l,host,selectedDomains.contains(host));check.setOnCheckedChangeListener((v,checked)->{if(checked)selectedDomains.add(host);else selectedDomains.remove(host);});}
  EditText extra=Ui.field(l,"Additional domains (comma separated)","",false),warnings=Ui.field(l,"Warning minutes before start (blank disables)",join(s.warnings),false);CheckBox enabled=Ui.check(l,"Enabled",s.enabled),strict=Ui.check(l,"Strict: bypass requires at least 60 seconds",s.strict);Ui.text(l,"Overlaps combine. Strict profiles take display priority, then stable IDs. Owner editing remains available.",13,Ui.MUTED);
  RoomPanel d=dialog("Lockdown profile",l,()->{String n=name.getText().toString().trim();if(n.isEmpty())throw new IllegalArgumentException("Give this profile a name.");Rules.Schedule out=new Rules.Schedule();out.id=s.id;out.name=n;out.mode=modes[mode.getSelectedItemPosition()];out.start=Ui.time(start.getText().toString());out.end=Ui.time(end.getText().toString());out.days.clear();for(int i=0;i<7;i++)if(checks.get(i).isChecked())out.days.add(i+1);if(out.days.isEmpty())throw new IllegalArgumentException("Choose at least one start day.");out.apps.addAll(selectedApps);out.domains.addAll(selectedDomains);String e=extra.getText().toString().trim();if(!e.isEmpty())for(String raw:e.split(",")){String host=Rules.domain(raw);if(host.isEmpty())throw new IllegalArgumentException("Invalid domain: "+raw);out.domains.add(host);}out.warnings.clear();String w=warnings.getText().toString().trim();if(!w.isEmpty())for(String v:w.split(",")){int m=Integer.parseInt(v.trim());if(m<1||m>120)throw new IllegalArgumentException("Warning minutes must be 1–120.");out.warnings.add(m);}out.enabled=enabled.isChecked();out.strict=strict.isChecked();if(out.apps.isEmpty()&&out.domains.isEmpty())throw new IllegalArgumentException("Choose an app or domain.");int index=config.schedules.indexOf(existing);if(index<0)config.schedules.add(out);else config.schedules.set(index,out);save();});if(existing!=null)Ui.button(l,"Delete profile",()->removeSchedule(existing.id));d.show();
 }
 private String join(Collection<Integer>v){List<String>s=new ArrayList<>();for(int i:v)s.add(""+i);return String.join(",",s);}
 private void explain(String title,String why,Intent intent){new AlertDialog.Builder(this).setTitle(title).setMessage(why).setNegativeButton("Not now",null).setPositiveButton("Open Android settings",(d,w)->{try{startActivity(intent);}catch(Exception e){toast("This settings page is unavailable on your device.");}}).show();}
 private void settings(){
  Ui.text(body,"Settings & setup",28,Ui.WHITE);LinearLayout setup=Ui.card(body);Ui.text(setup,"1 · Enable Yuki’s guard",21,Ui.WHITE);guardLabel=Ui.text(setup,"Status: "+(GuardService.connected?"Connected":Device.accessibilityEnabled(this)?"Enabled; waiting for Android":"Disabled"),15,Ui.BLUE);
  Ui.secondary(setup,"Accessibility setup",()->explain("Allow Yuki to enforce your rules?","Yuki detects foreground apps and reads only supported browser address-bar nodes. It uses an accessibility overlay to intervene. No messages, page text or browsing history are saved or transmitted. You can disable it any time. Sideloaded apps may first need App info → menu → Allow restricted settings.",new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS)));
  Ui.text(setup,"2 · Daily allowances",21,Ui.WHITE);usageLabel=Ui.text(setup,Device.usageAllowed(this)?"Usage access granted":"Usage access not granted",15,Ui.BLUE);Ui.secondary(setup,"Usage access setup",()->explain("Allow usage access?","Android’s local activity timestamps measure foreground use since local midnight. Without access, scheduled/permanent restrictions work but timed allowances cannot be measured.",new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS,Uri.parse("package:"+getPackageName()))));
  Ui.text(setup,"3 · Advance warnings",21,Ui.WHITE);notificationLabel=Ui.text(setup,getSystemService(NotificationManager.class).areNotificationsEnabled()?"Notifications available":"Notifications disabled",15,Ui.BLUE);Ui.secondary(setup,"Notification setup",()->new AlertDialog.Builder(this).setTitle("Allow advance reminders?").setMessage("Notifications warn before schedules begin. Android may delay them under battery saving; enforcement does not depend on notification delivery.").setNegativeButton("Not now",null).setPositiveButton("Continue",(d,w)->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},3);else startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));}).show());
  Ui.text(setup,"Overlay is supplied by the accessibility service; no separate Draw over other apps permission is required.",14,Ui.MUTED);Ui.secondary(setup,"App & battery settings",()->explain("Service reliability","Some phones suspend accessibility services under aggressive battery management. Review battery restrictions if interventions stop. Android can still suspend or revoke services.",new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()))));
  LinearLayout prefs=Ui.card(body);Ui.text(prefs,"Your preferences",21,Ui.WHITE);Switch enabled=Ui.toggle(prefs,"Protection enabled",config.enabled),websites=Ui.toggle(prefs,"Supported-browser website blocking",config.websites),reactions=Ui.toggle(prefs,"Escalate repeated-attempt reactions",config.reactions);enabled.setOnCheckedChangeListener((b,v)->{config.enabled=v;});websites.setOnCheckedChangeListener((b,v)->{config.websites=v;});reactions.setOnCheckedChangeListener((b,v)->{config.reactions=v;});Switch reduced=Ui.toggle(prefs,"Reduce motion",draftReduced);reduced.setOnCheckedChangeListener((button,value)->draftReduced=value);Switch companion=Ui.toggle(prefs,"Pocket Yuki companion",draftCompanion);companion.setOnCheckedChangeListener((button,value)->draftCompanion=value);companionSizeControl(prefs);Ui.text(prefs,"Tap Pocket Yuki for Boop, Talk and Move. After Move, drag her to place her. Boop blows a kiss; Move picks her up by her hoodie. She blinks and wanders near her saved spot. She needs the guard connected and hides during lockouts, keyboard use, screen lock and while this app is open. Feed data is coming later.",14,Ui.MUTED);Switch wander=Ui.toggle(prefs,"Let Yuki wander nearby",draftWander);wander.setOnCheckedChangeListener((button,value)->draftWander=value);Ui.secondary(prefs,"Reset Yuki’s position",()->{resetPosition=true;toast("Her position will reset when you save and close.");});Ui.secondary(prefs,"Preview Yuki’s entrance",this::previewYuki);Ui.text(prefs,"Charcoal / icy blue · follows system font size",14,Ui.MUTED);
  Ui.secondary(prefs,"AI destination",this::aiDestination);
  Ui.secondary(prefs,"Emergency bypass preferences",this::bypassPreferences);Ui.secondary(prefs,"Start emergency bypass",()->bypass(false));if(store.bypassActive())Ui.secondary(prefs,"End bypass now",()->attempt(()->{save();savePresentation();store.clearBypass();openPage("Settings");}));
  LinearLayout diag=Ui.card(body);Ui.text(diag,"Diagnostics & privacy",21,Ui.WHITE);Ui.text(diag,GuardService.status+"\n"+GuardService.lastBrowserStatus+"\nTime zone: "+ZoneId.systemDefault()+"\nConfiguration: "+(store.error.isEmpty()?"readable":store.error)+"\nNo Internet permission. No analytics or ads. Talk to Yuki opens your chosen app.",14,Ui.MUTED);Ui.text(diag,"Website coverage depends on browser address-bar accessibility. Unsupported browsers, embedded webviews, hidden bars and updates may bypass it. Exempt browsers bypass domain rules too. For stronger coverage, restrict unsupported browser apps. Split-screen, force-stop and revoked permissions can weaken enforcement.",14,Ui.MUTED);
 }
 private void removeApp(String pkg){removal("removeApp",pkg,"Remove app rules",()->{config.apps.remove(pkg);for(Rules.Schedule schedule:config.schedules)schedule.apps.remove(pkg);});}
 private void removeDomain(String host){removal("removeDomain",host,"Remove site everywhere",()->{config.domains.remove(host);for(Rules.Schedule schedule:config.schedules)schedule.domains.remove(host);});}
 private void removeSchedule(String id){removal("removeSchedule",id,"Delete plan",()->config.schedules.removeIf(plan->plan.id.equals(id)));}
 private void removal(String kind,String key,String title,Runnable remove){editorKind=kind;editorKey=key;LinearLayout l=form();Ui.text(l,"Close with × to confirm this removal. Discard keeps the saved rules.",17,Ui.WHITE);dialog(title,l,()->{String before=encoded(config);try{remove.run();save();}catch(Exception e){try{config=Store.decode(before);}catch(Exception ignored){}throw e;}}).show();}
 private void aiDestination(){editorKind="ai";editorKey="";LinearLayout l=form();EditText pkg=Ui.field(l,"Android package",config.aiPackage,false),url=Ui.field(l,"Fallback HTTPS URL",config.aiUrl,false);dialog("Talk to Yuki",l,()->{String p=pkg.getText().toString().trim(),u=url.getText().toString().trim();if(!p.matches("[a-zA-Z][a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]+)+")||!u.startsWith("https://")||Rules.domain(u).isEmpty())throw new IllegalArgumentException("Enter a valid package and HTTPS URL.");config.aiPackage=p;config.aiUrl=u;save();}).show();}
 private void bypassPreferences(){editorKind="friction";editorKey="";LinearLayout l=form();EditText minutes=Ui.field(l,"Break duration: 1–60 minutes",""+config.bypassMinutes,true),seconds=Ui.field(l,"Countdown: 5–120 seconds",""+config.bypassWaitSeconds,true);dialog("Emergency friction",l,()->{int m=Integer.parseInt(minutes.getText().toString()),s=Integer.parseInt(seconds.getText().toString());if(m<1||m>60||s<5||s>120)throw new IllegalArgumentException("Use the displayed ranges.");config.bypassMinutes=m;config.bypassWaitSeconds=s;save();}).show();}
 private void timePicker(EditText field){field.setFocusable(false);field.setClickable(true);field.setContentDescription(field.getText()+", choose time");field.setOnClickListener(v->{int minute=Ui.time(field.getText().toString());new TimePickerDialog(this,(picker,h,m)->{field.setText(Ui.time(h*60+m));field.setContentDescription(field.getText()+", choose time");},minute/60,minute%60,true).show();});}
 private void previewYuki(){Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);View content=Intervention.create(this,"bedtime","Bedtime preview","Darling, it’s bedtime. Your feed can wait. ♡",1,()->d.dismiss(),()->{d.dismiss();Device.talk(this);},()->d.dismiss(),true);d.setContentView(content);if(d.getWindow()!=null){d.getWindow().setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT));d.getWindow().setDimAmount(0);}d.show();if(d.getWindow()!=null)d.getWindow().setLayout(-1,-1);}
 private void bypass(boolean strict){
  page="Talk";editorKind="bypass";editorKey="";for(Rules.Schedule s:config.schedules)if(s.strict&&s.occurrence(ZonedDateTime.now())!=null)strict=true;int wait=Math.max(config.bypassWaitSeconds,strict?60:0);LinearLayout l=form();Ui.text(l,"You retain control. Pause restrictions for "+config.bypassMinutes+" minutes. Your reason stays on this screen and is not saved. Closing this request does not start a break.",16,Ui.WHITE);EditText reason=Ui.field(l,"Why do you need a break?","",false);RoomPanel request=scene.createPanel("Emergency break",l,null,false);Button confirm=Ui.button(l,"Wait…",()->{ });long until=SystemClock.elapsedRealtime()+wait*1000L;
  confirm.setOnClickListener(v->{if(SystemClock.elapsedRealtime()<until)return;if(reason.getText().toString().trim().length()<4){toast("Enter a short reason first.");return;}try{save();savePresentation();store.bypass(config.bypassMinutes);request.dismiss();page="";editorKind="";scene.reply("Your break has started. Your rules resume automatically, Darling.");}catch(Exception e){toast("Could not save the bypass. You can still edit your rules.");}});
  Runnable countdown=new Runnable(){public void run(){if(!request.isShowing())return;long left=Math.max(0,(until-SystemClock.elapsedRealtime()+999)/1000);confirm.setText(left>0?"Wait "+left+"s":"Confirm break");confirm.setEnabled(left==0);if(left>0)handler.postDelayed(this,250);}};request.show();countdown.run();
 }
}
